block explorer
helius-labs/xray pull request #129
Opened 2023-03-18 11:30 UTC by ssamkkim

2023-03-19 18:35 UTC, qudo-code approved these changes

2023-03-19 18:35 UTC, qudo-code commented on apps/web/src/lib/trpc/routes/block-transactions.ts
> +    .output(
I feel like we should fix ts->zod before we add more things like this. Maybe we fix that after adding the nav stats.

2023-03-19 18:35 UTC, qudo-code commented on apps/web/src/lib/trpc/routes/block-transactions.ts
> +        let filteredTxs: TransactionWithInvocations[] | undefined =
Could we turn the above step into a reduce and not have to loop `transactions` twice? Hopefully we only have to loop any iterable one time if possible.

2023-03-19 18:35 UTC, qudo-code commented on apps/web/src/lib/trpc/routes/block-transactions.ts
> +            const lastTxIndex = filteredTxs.findIndex(
Here we are kind of looping over the same list again, might be able to be handled in the first loop.

2023-03-19 18:35 UTC, qudo-code commented on apps/web/src/lib/trpc/routes/block-transactions.ts
> +        const url = `https://api.helius.xyz/v0/transactions/?api-key=${HELIUS_KEY}`;
Lets design a system to manage our endpoint/rpc urls before we add more hard coded links too.

2023-03-19 18:35 UTC, qudo-code commented on apps/web/src/lib/trpc/routes/block-transactions.ts
> +        let filteredTxs: TransactionWithInvocations[] | undefined =
Going forward lets try to not shorthand things like transaction -> txn or message -> msg. Make this `filteredTransactions`.

2023-03-19 18:35 UTC, qudo-code commented on apps/web/src/lib/trpc/routes/block-transactions.ts
> +            });
This could be 
`transactions?.filter(({ invocations }) => !(invocations.has(voteFilter) && invocations.size === 1));`

But also not needed if refactor.

2023-03-19 18:35 UTC, qudo-code commented on apps/web/src/lib/trpc/routes/current-slot.ts
> +});
dope

2023-03-19 18:35 UTC, qudo-code commented on apps/web/src/routes/block/[slot]/+page.svelte
> +</div>
Lets move this to another PR like I was saying and do the other preliminary cleanup tasks and bring it back when ready. Looks good for the most part though. 

Oh, also the page component/refactor from spoon. Probably want that in before any new pages too.

2023-03-19 18:35 UTC, qudo-code commented on apps/web/src/routes/block/[slot]/+page.ts
> +};
starting to follow the future url patterns early? Lets also get those in if we do something like this, else adhere to existing.

2023-03-19 18:37 UTC, qudo-code requested changes

2023-03-19 18:37 UTC, qudo-code commented on apps/web/src/lib/components/stats.svelte
>      const tps = client.tps.createQuery();
Adding new comment because github is making me add a change to this review.

2023-03-20 01:41 UTC, ssamkkim commented on apps/web/src/lib/trpc/routes/block-transactions.ts
> +                for (const [i, count] of indexMap.entries()) {
yea I jsut did it like this because I copied how the solana explorer code did it

2023-03-20 01:52 UTC, ssamkkim commented on apps/web/src/lib/trpc/routes/block-transactions.ts
> +            });
maybe for now but not later because that filter will depend on filter options (ex: user opting into showing vote txs)

2023-03-20 01:53 UTC, ssamkkim commented on apps/web/src/routes/block/[slot]/+page.ts
> +};
wdym? and yea idk tbh I just did wtv I could do to make it work

2023-03-20 01:56 UTC, ssamkkim commented on apps/web/src/lib/components/stats.svelte
> +    const slot = client.currentSlot.createQuery();
ok, what do you think of the overall layout of the slot stat?

2023-03-24 23:04 UTC, qudo-code commented on apps/web/src/routes/block/[slot]/+page.ts
> +};
Noticed the route is /block/id not /id/block

2023-03-24 23:04 UTC, qudo-code commented on apps/web/src/lib/trpc/routes/block-transactions.ts
> +            });
I say we should write optimized code for today if possible. Right now it looks like an orphan return kinda.

2023-03-27 22:16 UTC, qudo-code approved these changes

2023-03-27 22:26 UTC, merged